import Head from 'next/head';
import { Navbar } from '../components/navbar';
import { BoardProvider } from '../modules/board/board.provider';

export default function Board() {
  return (
    <BoardProvider>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
      </div>
    </BoardProvider>
  );
}
