import Head from 'next/head';
import { Navbar } from '../components/navbar';
import { dehydrate, QueryClient } from 'react-query';
import { BoardProvider } from '../modules/board/board.provider';
import { getIssues } from '../modules/board/board.api';
import { Kanban } from '../components/kanban';

export default function Board() {
  return (
    <BoardProvider>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
      </div>
      <Kanban />
    </BoardProvider>
  );
}

/* export const getServerSideProps = async () => {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery('issues', getIssues);

  return {
    props: { dehydratedState: dehydrate(queryClient) },
  };
};
 */
