import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Navbar } from '../components/navbar';
import { HomeProvider } from '../modules/home';

export default function Home() {
  return (
    <HomeProvider>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
      </div>
    </HomeProvider>
  );
}
