name: Deployment

on:
  push:
    branches:
      - main
      - feature/configure-serverless-nextjs

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn
      - run: env
      - run: env >> .env.local
      - run: yarn run sls
